## Create a DataFrame by customized data

In [2]:
# Create two-dimensional, size-mutable, potentially heterogeneous tabular data by yourself.
# Please understand how pd.DataFrame works via:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

# {'key1': [], 'key2': [], ...} is a dictionary in Python

import pandas as pd
df1 = pd.DataFrame({'name': ['Jason', 'Lucy', 'Helen'], 'height': [180, 170, 165], 'weight': [75, 65, 72]}) 
df1

    name  height  weight
0  Jason     180      75
1   Lucy     170      65
2  Helen     165      72

In [3]:
df2 = pd.DataFrame({'name': ['Jason', 'Lucy', 'Helen'], 'mathematics': [80, 90, 65], 'science': [75, 65, 72]})
df2

    name  mathematics  science
0  Jason           80       75
1   Lucy           90       65
2  Helen           65       72

In [4]:
df3 = pd.DataFrame({'name': ['Jason', 'Lucy', 'Helen'], 'company': ['RMIT', 'RMIT', 'RMIT'], 'salary': [100000, '120,000', '110,000']})
df3

    name company   salary
0  Jason    RMIT   100000
1   Lucy    RMIT  120,000
2  Helen    RMIT  110,000

In [5]:
df4 = pd.DataFrame({'name': ['Jason', 'Lucy', 'Helen'], '# of attendance': [22, 22, 15]})
df4

    name  # of attendance
0  Jason               22
1   Lucy               22
2  Helen               15

## Merge different DataFrames by 'name'

In [6]:
# Merge DataFrame or named Series objects with a database-style join.
# Please understand how merge() function works via:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html#pandas.DataFrame.merge

merged_df = df1.merge(df2, on='name', how='inner')
merged_df = merged_df.merge(df3, on='name', how='inner')
merged_df = merged_df.merge(df4, on='name', how='inner')
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",15

In [7]:
# Use Method Chain

merged_df = df1.merge(df2, on='name', how='inner').merge(df3, on='name', how='inner').merge(df4, on='name', how='inner')
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",15

In [8]:
# Use For loop

all_df = [df2, df3, df4]
merged_df = df1
for df in all_df:
    merged_df = merged_df.merge(df, on='name', how='inner')
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",15

## Add new observation to merged_df

In [9]:
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",15

In [10]:
# A part of Helen's attendance is recorded into another dataset, which needs to be added to merged_df
new_df = pd.DataFrame([{'name': 'Helen', 'height': 165, 'weight': 72, 'mathematics': 65, 
                              'science': 72, 'company': 'RMIT', 
                              'salary': '110,000', '# of attendance': 6}])

In [11]:
merged_df = pd.concat([merged_df, new_df], ignore_index=True)

## The rows with index 2 and 3 are recorded separately for the same staff, which needs to merge to one row.

In [12]:
# groupby(): Group DataFrame using a mapper or by a Series of columns.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html

# transform(): Call function producing a like-indexed Series on each group and return a Series 
# having the same indexes as the original object filled with the transformed values.
# Please refer to: 
# https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.SeriesGroupBy.transform.html

merged_df['# of attendance'] = merged_df.groupby(['name', 'height', 'weight', 'mathematics', 'science', 
                                                  'company', 'salary'])['# of attendance'].transform('sum') # use the return values of sum() function as the transformed values
merged_df['# of attendance']

0    22
1    22
2    21
3    21
Name: # of attendance, dtype: int64

## Remove duplicates

In [13]:
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",21
3,Helen,165,72,65,72,RMIT,"110,000",21

In [14]:
# Return DataFrame with duplicate rows removed.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html

merged_df = merged_df.drop_duplicates(subset=['name', 'height', 'weight', 'mathematics', 'science', 
                                              'company', 'salary']).reset_index(drop=True)
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,"120,000",22
2,Helen,165,72,65,72,RMIT,"110,000",21

## Transfer 'salary' to numbers

In [15]:
# Use astype to transform data type
# astype(): Cast a pandas object to a specified dtype dtype.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.Series.astype.html

# str.replace(): Replace each occurrence of pattern/regex in the Series/Index.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html

merged_df['salary'] = merged_df['salary'].astype('str').str.replace(',', '').astype('int')
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,120000,22
2,Helen,165,72,65,72,RMIT,110000,21

In [16]:
# Or use pd.to_numeric
# Convert argument to a numeric type.
# Please refer to: https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html

merged_df['salary'] = pd.to_numeric(merged_df['salary'].astype('str').str.replace(',', ''))
merged_df

,name,height,weight,mathematics,science,company,salary,# of attendance
0,Jason,180,75,80,75,RMIT,100000,22
1,Lucy,170,65,90,65,RMIT,120000,22
2,Helen,165,72,65,72,RMIT,110000,21